oxio_dms/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.auth import urls as auth_urls
from django.views.static import serve

from oxio_dms import settings
from profiles import views as profile_views
from document import views as document_views

urlpatterns = [
    path('', profile_views.home_page, name='home_page'),
    path('accounts/password_change/',profile_views.change_password,name='change_password'),
    path('accounts/', include(('django.contrib.auth.urls','accounts'))),
    path('accounts/signup/', profile_views.signup, name='signup'),
    path('accounts/profile/',profile_views.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('keys/',profile_views.add_key),
    path('keys/delete/<int:key_id>/',profile_views.remove_key),
    path('document/', document_views.document),
    path('document/create/', document_views.document_create),
    path('document/info/<int:document_id>/',document_views.document_info),
    path('document/delete/<int:document_id>/',document_views.document_delete),
    path('document/add_revision/<int:document_id>/',document_views.add_revision),
    path('document/revisions/<int:document_id>/',document_views.document_revisions),
    path('document/share/<int:document_id>/',document_views.document_share),
    path('document/add_comment/<int:document_id>/',document_views.add_comment),
    path('document/check_out/<int:document_id>/',document_views.document_check_out),
    path('document/check_in/<int:document_id>/',document_views.document_check_in),
    path('document/shared/', document_views.document_shared),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^document_storage/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

document/models.py
from itertools import chain
import gnupg
import base64
import logging
import pdb

from django.db import models
from django.contrib.auth.models import User

from document import crypto_settings
from document import workflow

CREATE_ACTION ='C'
READ_ACTION = 'R'
DELETE_ACTION = 'D'
CHECK_IN_ACTION ='I'
CHECK_OUT_ACTION = 'O'

class Document(models.Model):
    WORKFLOW_CHOICES = (
        ( workflow.COLLABORATION_WORKFLOW, "Collaboration" ),
        ( workflow.APPROVAL_WORKFLOW, "Approval"),
    )
    STATE_CHOICES = (
        (workflow.PRIVATE_STATE,"Private Document"),
        (workflow.COLLABORATION_STATE, "Collaboration"),
        (workflow.ARCHIVED_STATE, "Archived Document"),
        (workflow.SENT_FOR_APPROVAL_STATE, "Sent For Approval"),
        (workflow.APPROVED_STATE, "Approved"),
        (workflow.RETURNED_STATE,"Returned Document")
    )
    document_name = models.CharField( max_length=300 )
    document_creation_date = models.DateTimeField(auto_now = True)
    document_user = models.ForeignKey(
        User, on_delete = models.CASCADE,
        related_name='document_owner_rel'
    )
    document_is_checked_out = models.BooleanField(default = False)
    document_shared_to_users = models.ManyToManyField(User, related_name = 'document_set')
    document_workflow = models.CharField(
        max_length=1,
        choices = WORKFLOW_CHOICES,
        default = workflow.COLLABORATION_WORKFLOW
    )
    document_state = models.CharField(
        max_length = 1,
        choices = STATE_CHOICES,
        default = workflow.PRIVATE_STATE
    )

    def send_to(self, user):
        return self.document_shared_to_users.add(user)

    def last_revision_download(self):
        try:
            last_revision = Revision.objects.filter(revision_document = self).order_by('-id')[0]
            return last_revision.revision_contents.url
        except IndexError:
            return False

    def get_comments(self):
        return DocumentComment.objects.filter(comment_document = self)

    def check_in(self, user):
        self.document_is_checked_out = False
        self.save()

    def check_out(self, user):
        self.document_is_checked_out = True
        self.save()

    def get_allowed_users(self):
        shared_users = self.document_shared_to_users.all()
        return chain((self.document_user,), shared_users)

    def __str__(self):
        return self.document_name


class Revision(models.Model):
    revision_document = models.ForeignKey(Document, on_delete = models.CASCADE)
    revision_time = models.DateTimeField(auto_now = True)
    revision_contents = models.FileField(upload_to="document_storage/")
    revision_signature = models.FileField(upload_to="signature_storage/", blank=True)
    revision_user = models.ForeignKey(User,on_delete = models.CASCADE)

    def verify_signature(self):
        gpg = gnupg.GPG(gnupghome=crypto_settings.GPG_HOME)
        file_location = self.revision_contents.path
        signature_location = open(self.revision_signature.path,'rb')
        result = gpg.verify_file(signature_location, file_location)
        logging.info(result.trust_level)
        if result.trust_level != None:
            current_signature = Signature(
                signature_revision = self,
                signature_username = result.username,
                signature_key_id = result.key_id,
                signature_id = result.signature_id,
                signature_fingerprint = result.fingerprint,
                signature_trust_level = result.trust_level,
                signature_trust_text = result.trust_text
            )
            current_signature.save()
            self.save()
            return True
        else:
            return False

    def get_signature(self):
        try:
            current_signature = Signature.objects.get(signature_revision__pk = self.pk)
        except Signature.DoesNotExist:
            current_signature = None
        return current_signature
    
    def save(self):
        new_log = DocumentLog(
            document_log_user_login = self.revision_user,
            document_log_document_name = self.revision_document,
            document_log_revision = self,
            document_log_action = CREATE_ACTION
        )
        new_log.save()
        return super().save()
            

class Signature(models.Model):
    signature_username = models.TextField()
    signature_key_id = models.TextField()
    signature_id = models.TextField()
    signature_fingerprint = models.TextField()
    signature_trust_level = models.TextField()
    signature_trust_text = models.TextField()
    signature_revision = models.OneToOneField(Revision, on_delete = models.CASCADE)


class DocumentLog(models.Model):
    ACTION_CHOICES = (
        (CREATE_ACTION, 'Create'),
        (READ_ACTION, 'Read'),
        (DELETE_ACTION, 'Delete'),
        (CHECK_IN_ACTION, 'Check-In'),
        (CHECK_OUT_ACTION, 'Check-Out')
    )

    document_log_user_login = models.CharField( max_length = 300 )
    document_log_document_name = models.CharField( max_length = 300 )
    document_log_revision = models.CharField( max_length = 300 )
    document_log_time = models.DateTimeField(auto_now = True)
    document_log_action = models.TextField(max_length = 1, choices = ACTION_CHOICES)

class DocumentComment(models.Model):
    comment_contents = models.TextField(max_length = 300)
    comment_document = models.ForeignKey(Document, on_delete = models.CASCADE)
    comment_date = models.DateTimeField(auto_now = True)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)

document/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models

class CreateDocumentForm(forms.ModelForm):
    class Meta:
        model = models.Document
        fields = ('document_name','document_workflow')

class CreateRevisionForm(forms.ModelForm):
    class Meta:
        model = models.Revision
        fields = ('revision_contents','revision_signature')

class DocumentShareForm(forms.Form):
    user_field = forms.ModelMultipleChoiceField(User.objects.all())

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = models.DocumentComment
        fields = ('comment_contents',)

document/views.py
import pdb

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden
from django.core.files.storage import FileSystemStorage
from django.forms import ModelMultipleChoiceField
from django.contrib.auth.models import User
#from django.core.exceptions import 

from . import forms
from . import models

def document(request):
    if request.user.is_authenticated:
        users_documents = models.Document.objects.filter(
            document_user_id = request.user.id
        )
        return render(request, 'document.html',{
            'users_documents':users_documents,
            'nbar': 'documents'
        })
    else:
        return redirect('/accounts/login/')

def document_create(request):
    if request.method == 'POST' and request.user.is_authenticated:
        document_form = forms.CreateDocumentForm(request.POST)
        if document_form.is_valid():
            new_document = models.Document(
                document_name = document_form.cleaned_data['document_name'],
                document_user = request.user
            )
            new_document.save()
        return redirect('/document/')
    else:
        document_form = forms.CreateDocumentForm()
        return render(request,'document_create.html',{
            'document_form':document_form,
            'nbar': 'documents'
        })

def document_info(request, document_id):
    current_document = models.Document.objects.get(pk=document_id)
    allowed_users = current_document.document_shared_to_users.all()
    last_revision_link = current_document.last_revision_download()
    document_comments = current_document.get_comments()
    add_comment_form = forms.AddCommentForm(request.POST)
    is_document_owner = (current_document.document_user == request.user)
    return render(request,'document_info.html',{
        'document':current_document,
        'last_revision_download':last_revision_link,
        'shared_users':current_document.document_shared_to_users.all(),
        'nbar': 'documents',
        'comments':document_comments,
        'add_comment_form':add_comment_form,
        'is_document_owner':is_document_owner
    })

def add_comment(request, document_id):
    if request.method == 'POST' and request.user.is_authenticated:
        current_form = forms.AddCommentForm(request.POST)
        if current_form.is_valid():
            new_comment = models.DocumentComment (
                comment_contents = current_form.cleaned_data['comment_contents'],
                comment_document = models.Document.objects.get(pk = document_id),
                comment_user = request.user
            )
            new_comment.save()
        return redirect("/document/info/"+str(document_id)+'/')
    else:
        return redirect("/accounts/login/")

def document_delete(request, document_id):
    models.Document.objects.get(pk = document_id).delete()
    return redirect('/document/')

def add_revision(request, document_id):
    if request.method == 'POST' and request.user.is_authenticated:
        revision_form = forms.CreateRevisionForm(request.POST, request.FILES)
        if revision_form.is_valid():
            current_document = models.Document.objects.get( pk = document_id )
            if current_document.document_is_checked_out == False:
                myfile = request.FILES['revision_contents']
                myfile_signature = request.FILES['revision_signature']
                created_revision = models.Revision(
                    revision_document = current_document,
                    revision_contents = myfile,
                    revision_signature = myfile_signature,
                    revision_user = request.user
                )
                created_revision.save()
                created_revision.verify_signature()
        return redirect('/document/info/'+str(document_id)+'/')
    else:
        revision_form = forms.CreateRevisionForm(request.POST)
        return render(request,'revision_create.html',{
            'revision_form':revision_form,
            'nbar': 'documents'
        })

def document_share(request, document_id):
    if request.method == 'POST' and request.user.is_authenticated:
        current_form = forms.DocumentShareForm(request.POST)
        if current_form.is_valid():
            current_document = models.Document.objects.get(pk=document_id)
            for user in current_form.cleaned_data['user_field']:
                current_document.send_to(user)
        return redirect('/document/info/'+str(document_id)+'/')
    else:
        current_form = forms.DocumentShareForm()
        return render(request, 'document_share.html', {
            'share_form':current_form,
            'nbar': 'documents'
        })

def document_check_out(request, document_id):
    current_document = models.Document.objects.get( pk=document_id )
    if request.user != current_document.document_user:
        return HttpResponseForbidden()
    else:
        current_document.check_out(request.user)
        return redirect('/document/info/'+str(document_id)+'/')

def document_check_in(request, document_id):
    current_document = models.Document.objects.get( pk=document_id )
    if request.user != current_document.document_user:
        return HttpResponseForbidden()
    else:
        current_document.check_in(request.user)
        return redirect('/document/info/'+str(document_id)+'/')

def document_revisions(request, document_id):
    revisions = models.Revision.objects.filter(revision_document__pk=document_id)
    for revision in revisions:
        revision.signature_status = revision.get_signature()
    #pdb.set_trace()
    return render(request, 'document_revisions.html',{
        'revisions': revisions,
        'document_id': document_id,
        'nbar': 'documents'
    })

def document_shared(request):
    if request.user.is_authenticated:
        current_user = request.user
        user_shared_documents = current_user.document_set.all()
        return render(request,'document_shared.html',{
            'shared_documents':user_shared_documents,
            'nbar': 'shared'
        })
    else:
        return redirect("/accounts/login/")

document/templates/document.html
{% extends 'base.html' %}

{% block title %}Document{% endblock %}

{% block content %}
  <h1>Document</h1>

  <p><a id="new_document_button" href="/document/create/">Create Document</a></p>

  <hr>
  <table id="documents_table" class="table-bordered" border="2">
    <tr>
      <th>Document Name</th>
      <th>Document Info</th>
      <th>Add Revision</th>
      <th>Delete</th>
      <th>Share</th>
    </tr>
    {% for document in users_documents %}
      <tr>
        <td class="document_name"><p>{{ document.document_name }}</p></td>
        <td class="document_info"><a href="/document/info/{{ document.pk }}/"><p>Document Info</p></a></td>
        <td class="document_revision"><a href="/document/add_revision/{{ document.pk }}/"><p>Add Revision to Document</p></a></td>
        <td class="document_delete"><a href="/document/delete/{{ document.pk }}/"><p>Delete Document</p></a></td>
        <td class="document_share"><a href="/document/share/{{ document.pk }}/"><p>Share Document</p></a></td>

      </tr>
      {% empty %}
        <tr><p>No documents present. Please create a document by clicking on "Create Document"</p></tr>
      {% endfor %}
  </table>

{% endblock %}

document/templates/document_create.html
{% extends 'base.html' %}

{% block title %}Create Document{% endblock %}

{% block content %}
  <h1>Create Document</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ document_form.as_p }}

    <button id="document_submit_button_id" type="submit" class="btn btn-default">Create Document</button>
  </form>
{% endblock %}

document/templates/document_info.html
{% extends 'base.html' %}

{% block title %}Document Information{% endblock %}

{% block content %}
  <h1>Document Information</h1>
  <p id="id_document_name">Document Name: {{ document.document_name }} </p>
  <p id="id_document_user">Created By: {{ document.document_user.username }} </p>
  {% if last_revision_download != False %}
    <p id="id_latest_revision">Last Revision: <a href = {{ last_revision_download }}>Download</a> </p>
  {% else %}
    <p>No revisions found. Click <a href="/document/add_revision/{{ document.pk }}/">here</a> to add a revision </p>
  {% endif %}
  {% if is_document_owner == True and document.document_is_checked_out == False %}
    <a id="id_document_check_out" href="/document/check_out/{{document.pk}}/">Check Out</a>
  {% elif is_document_owner == True and document.document_is_checked_out == True %}
    <a id="id_document_check_in" href="/document/check_in/{{document.pk}}/">Check In</a>
  {% endif %}

  <p><a id="id_document_revision_list" href="/document/revisions/{{ document.pk }}/">Document Revisions</a></p>
  <p><a href="/document/share/{{ document.pk }}/">Share Document</a></p>
  <p>Shared with users:</p>
  {% for user in shared_users %}
    <p class="users_shared">{{ user.username }}</p>
  {% empty %}
    <p>No users</p>
  {% endfor %}

  <p>Comments</p>
  {% for comment in comments %}
    <p>{{ comment.comment_user }} {{ comment.comment_date }}: {{ comment.comment_contents }}</p>
  {% empty %}
    <p>No Comments</p>
  {% endfor %}
  <h2>Add Comment</h2>
  <form method="post" action="/document/add_comment/{{ document.pk }}/">
    {% csrf_token %}
    {{ add_comment_form.as_p }}
    <button id="add_comment_button_id" type="submit" class="btn btn-default">Add Comment</button>
  </form>
{% endblock %}

document/templates/document_revisions.html
{% extends 'base.html' %}

{% block title %}Document Revisions{% endblock %}

{% block content %}
  <h1>Document Revisions</h1>

  <hr>
  <table id="documents_revisions_table" border="2">
    <tr>
      <td><p>Document Name</p></td>
      <td><p>Download Revision</p></td>
      <td><p>Creation Date</p></td>
      <td><p>Revision Status</p></td>
    </tr>
    {% for revision in revisions %}
      <tr>
        <td><p class="revision_document">{{ revision.revision_document.document_name }}</p></td>
        <td><a class="revision_download" href="{{ revision.revision_contents.url }}")>Download<p ></p></a></td>
        <td><p class="revision_date">{{ revision.revision_time }}</p></td>
        <td><p class="revision_status">
        {% if revision.signature_status.signature_username != None %}
          Signed By: {{ revision.signature_status.signature_username }}
        {% else %} 
          Unsigned
        {% endif %}
        </p></td>
      </tr>
      {% empty %}
        <tr><p>No revisions present. Please create a revision by clicking on "Create Revision"</p></tr>
      {% endfor %}
  </table>
  <a id="id_create_revision" href="/document/add_revision/{{ document_id }}/">Create Revision</a>

{% endblock %}

document/templates/document_share.html
{% extends 'base.html' %}

{% block title %}Share Document{% endblock %}

{% block content %}
  <h1>Share Document</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ share_form.as_p }}

    <button id="document_share_button_id" type="submit" class="btn btn-default">Share Document</button>
  </form>
{% endblock %}

document/templates/document_shared.html
{% extends 'base.html' %}

{% block title %}Shared documents{% endblock %}

{% block content %}
  <h1>Documents shared to you</h1>
  <table id="documents_table" class="table-bordered"  border="2">
    <tr>
      <th>Document Name</th>
      <th>Document User</th>
      <th>Document Info</th>
      <th>Add Revision</th>
      <th>Share</th>
    </tr>

  {% for document in shared_documents %}
    <tr>
       <td class="document_name"><p>{{ document.document_name }}</p></td>
       <td class="document_user"><p>{{ document.document_user }}</p></td>
       <td class="document_info"><a href="/document/info/{{ document.pk }}/"><p>Document Info</p></a></td>
       <td class="document_revision"><a href="/document/add_revision/{{ document.pk }}/"><p>Add Revision to Document</p></a></td>
       <td class="document_share"><a href="/document/share/{{ document.pk }}/"><p>Share Document</p></a></td>
    </tr>
    {% empty %}
      <tr><p>No documents present.</p></tr>
    {% endfor %}
  </table>
{% endblock %}

document/templates/revision_create.html
{% extends 'base.html' %}

{% block title %}Create Revision{% endblock %}

{% block content %}
  <h1>Create Revision</h1>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ revision_form.as_p }}
  <button id="id_revision_submit_button" type="submit" class="btn btn-default">Create Revision</button>
  </form>
{% endblock %}